# Netlify configuration for Garp documentation site

[build]
  # Build command - uses our custom build script
  command = "scripts/build-docs.sh"
  
  # Directory to publish
  publish = "site"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    GO_VERSION = "1.21"
    HUGO_VERSION = "0.119.0"

# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_pagefind/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects and rewrites
[[redirects]]
  from = "/docs"
  to = "/docs/"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog/"  
  status = 301

# Handle trailing slashes for clean URLs
[[redirects]]
  from = "/docs/*/"
  to = "/docs/:splat"
  status = 200

[[redirects]]
  from = "/blog/*/"  
  to = "/blog/:splat"
  status = 200

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://garp-docs.netlify.app"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]

# Deploy contexts
[context.production]
  command = "scripts/build-docs.sh"

[context.deploy-preview]
  command = "scripts/build-docs.sh"

[context.branch-deploy]
  command = "scripts/build-docs.sh"

# Development context
[context.dev]
  command = "scripts/build-docs.sh --css-only"

# Split testing (optional)
[split_testing]
  [[split_testing.features]]
    path = "/docs/*"
    percentage = 50