# Cloudflare Pages configuration for Garp documentation site
name = "garp-docs"
compatibility_date = "2024-01-15"

# Build configuration
[build]
command = "scripts/build-docs.sh"
cwd = "."
watch_dir = "site"

[build.upload]
format = "directory"
dir = "site"
include = ["**/*"]
exclude = [
  "*.log",
  "build-report.json",
  "Caddyfile",
  "node_modules",
  ".git"
]

# Environment variables
[env.production]
NODE_VERSION = "18"
GO_VERSION = "1.21"

[env.preview]
NODE_VERSION = "18" 
GO_VERSION = "1.21"

# Custom domains (configure in Cloudflare dashboard)
# route = { pattern = "docs.garp.dev", zone_name = "garp.dev" }

# Security headers
[site]
include = ["site/*"]
exclude = ["site/Caddyfile"]

# Cache rules
[[redirects]]
from = "/docs"
to = "/docs/"
status = 301

[[redirects]]
from = "/blog"
to = "/blog/"
status = 301

# Custom headers via _headers file (Cloudflare Pages format)
# This configuration applies to all routes